# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65a2e5b2bc911ed49f57223fb9e979798c38c044780b0f242dbebcd5191b38fcba9886c2d30b302f661668fb73c917d9616acc695ebadcd3239e84c9f7b50b5a

test:
  secret_key_base: f51052f6c7f3f029285d69641298a414df1760bb45ff90418019de8c177dbd96a5abcf8f6c66e443a9d8a37f4812ce71f6d8bebddfcc5b148a52b6eac856f1a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
