application: cruzalinhas2
version: 3
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  
- url: /
  static_files: static/cruzalinhas.html
  upload: static/cruzalinhas.html

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  
- url: /
  script: frontend.py
    
- url: /linha.json
  script: frontend.py
    
- url: /linhasquepassam.json
  script: frontend.py

- url: /robots.txt
  script: frontend.py

- url: /.*
  script: frontend.py
  login: admin


